-- seed.sql
-- Mock dataset mirroring the structure of the final trafficking-incident data.
-- Runs automatically on first container init (mounted into
-- /docker-entrypoint-initdb.d/). Edit + `docker compose down -v && up -d` to reseed.
-- ~100 rows generated with weighted distributions so aggregations have shape.

DROP TABLE IF EXISTS incidents;

CREATE TABLE incidents (
    id                      SERIAL PRIMARY KEY,
    article_url             TEXT NOT NULL,
    article_title           TEXT,
    article_domain          TEXT,
    reported_date           DATE,
    incident_date           DATE,
    location_country        TEXT,
    location_region         TEXT,
    crime_type              TEXT,
    victim_count            INTEGER,
    victim_nationality      TEXT,
    perpetrator_nationality TEXT,
    summary                 TEXT,
    confidence              TEXT
);

ALTER TABLE incidents
    ADD CONSTRAINT chk_region CHECK (location_region IN (
        'Southeast Asia', 'East Asia', 'South Asia',
        'East Africa', 'West Africa', 'Central Africa', 'Southern Africa',
        'Europe', 'North America', 'Central America', 'South America',
        'Middle East', 'Pacific', 'Other'
    )),
    ADD CONSTRAINT chk_crime_type CHECK (crime_type IN (
        'pig_butchering', 'scam_compound', 'forced_labour', 'sex_trafficking',
        'organ_trafficking', 'debt_bondage', 'smuggling', 'other'
    )),
    ADD CONSTRAINT chk_confidence CHECK (confidence IN ('high', 'medium', 'low'));

INSERT INTO incidents (
    article_url, article_title, article_domain, reported_date, incident_date,
    location_country, location_region, crime_type, victim_count,
    victim_nationality, perpetrator_nationality, summary, confidence
) VALUES
('https://africareport.example.com/article-1', 'Investment scam ring dismantled', 'africareport.example.com', '2025-03-08', NULL, 'Romania', 'Europe', 'pig_butchering', NULL, NULL, NULL, 'Reported incident of pig butchering in Romania.', 'medium'),
('https://news.example.com/article-2', 'Victims freed in operation', 'news.example.com', '2025-12-15', '2024-06-12', 'Myanmar', 'Southeast Asia', 'sex_trafficking', 141, 'Brazilian', NULL, 'Reported incident of sex trafficking in Myanmar.', 'medium'),
('https://chronicle.example.org/article-3', 'Cross-border ring disrupted', 'chronicle.example.org', '2024-10-27', NULL, 'Thailand', 'Southeast Asia', 'scam_compound', 315, 'Mixed', 'Indian', 'Reported incident of scam compound in Thailand.', 'high'),
('https://eastafricawire.example.net/article-4', 'Arrests in exploitation probe', 'eastafricawire.example.net', '2025-01-14', '2024-06-15', 'UK', 'Europe', 'smuggling', 342, 'Indian', 'Vietnamese', 'Reported incident of smuggling in UK.', 'medium'),
('https://globalpost.example.net/article-5', 'Labour abuse allegations surface', 'globalpost.example.net', '2024-08-22', '2024-02-27', 'USA', 'North America', 'forced_labour', 160, 'Indian', NULL, 'Reported incident of forced labour in USA.', 'medium'),
('https://dailywire.example.org/article-6', 'Labour abuse allegations surface', 'dailywire.example.org', '2025-07-28', NULL, 'Saudi Arabia', 'Middle East', 'forced_labour', 381, 'American', 'Filipino', 'Reported incident of forced labour in Saudi Arabia.', 'medium'),
('https://chronicle.example.org/article-7', 'Migrant workers report abuse', 'chronicle.example.org', '2025-01-25', '2025-01-29', 'DR Congo', 'Central Africa', 'debt_bondage', 238, 'Thai', 'Nepali', 'Reported incident of debt bondage in DR Congo.', 'low'),
('https://eastafricawire.example.net/article-8', 'Migrant workers report abuse', 'eastafricawire.example.net', '2025-05-27', '2024-09-26', 'Saudi Arabia', 'Middle East', 'pig_butchering', 258, 'Mexican', 'Sudanese', 'Reported incident of pig butchering in Saudi Arabia.', 'medium'),
('https://africareport.example.com/article-9', 'Cross-border ring disrupted', 'africareport.example.com', '2024-04-24', '2024-01-20', 'South Korea', 'East Asia', 'forced_labour', 156, 'Nigerian', 'Indian', 'Reported incident of forced labour in South Korea.', 'high'),
('https://chronicle.example.org/article-10', 'Migrant workers report abuse', 'chronicle.example.org', '2024-09-28', '2024-06-18', 'USA', 'North America', 'other', 309, 'Romanian', 'Romanian', 'Reported incident of other in USA.', 'low'),
('https://dailywire.example.org/article-11', 'Trafficking network broken up', 'dailywire.example.org', '2025-07-21', NULL, 'Bangladesh', 'South Asia', 'sex_trafficking', 111, NULL, 'Chinese', 'Reported incident of sex trafficking in Bangladesh.', 'high'),
('https://africareport.example.com/article-12', 'Labour abuse allegations surface', 'africareport.example.com', '2025-08-07', NULL, 'Cambodia', 'Southeast Asia', 'scam_compound', 123, 'British', NULL, 'Reported incident of scam compound in Cambodia.', 'high'),
('https://eastafricawire.example.net/article-13', 'Compound raid frees workers', 'eastafricawire.example.net', '2025-02-16', NULL, 'UK', 'Europe', 'sex_trafficking', 54, 'Romanian', 'Filipino', 'Reported incident of sex trafficking in UK.', 'medium'),
('https://eastafricawire.example.net/article-14', 'Cross-border ring disrupted', 'eastafricawire.example.net', '2024-04-05', '2024-01-16', 'Taiwan', 'East Asia', 'pig_butchering', 120, 'Egyptian', 'American', 'Reported incident of pig butchering in Taiwan.', 'high'),
('https://eastafricawire.example.net/article-15', 'Victims freed in operation', 'eastafricawire.example.net', '2025-11-08', '2025-07-23', 'China', 'East Asia', 'pig_butchering', 78, 'Romanian', 'Chinese', 'Reported incident of pig butchering in China.', 'low'),
('https://africareport.example.com/article-16', 'Cross-border ring disrupted', 'africareport.example.com', '2024-07-09', NULL, 'India', 'South Asia', 'sex_trafficking', NULL, NULL, 'American', 'Reported incident of sex trafficking in India.', 'high'),
('https://eastafricawire.example.net/article-17', NULL, 'eastafricawire.example.net', '2024-11-19', '2025-06-19', 'Fiji', 'Pacific', 'forced_labour', 103, 'Brazilian', NULL, 'Reported incident of forced labour in Fiji.', 'medium'),
('https://news.example.com/article-18', 'Investment scam ring dismantled', NULL, '2024-04-12', '2025-07-30', 'Philippines', 'Southeast Asia', 'pig_butchering', NULL, 'Kenyan', NULL, 'Reported incident of pig butchering in Philippines.', 'medium'),
('https://africareport.example.com/article-19', 'Cross-border ring disrupted', 'africareport.example.com', '2025-06-25', '2025-10-31', 'UAE', 'Middle East', 'forced_labour', NULL, 'Mexican', 'Nepali', 'Reported incident of forced labour in UAE.', 'high'),
('https://globalpost.example.net/article-20', 'Trafficking network broken up', 'globalpost.example.net', '2025-06-01', '2024-09-27', 'India', 'South Asia', 'scam_compound', 25, NULL, 'Kenyan', 'Reported incident of scam compound in India.', 'high'),
('https://chronicle.example.org/article-21', 'Victims freed in operation', 'chronicle.example.org', '2024-03-18', '2024-04-24', 'Myanmar', 'Southeast Asia', 'pig_butchering', 352, 'Chinese', 'Filipino', 'Reported incident of pig butchering in Myanmar.', 'medium'),
('https://eastafricawire.example.net/article-22', 'Trafficking network broken up', 'eastafricawire.example.net', '2025-07-27', NULL, 'Thailand', 'Southeast Asia', 'scam_compound', 207, 'Filipino', 'Nigerian', 'Reported incident of scam compound in Thailand.', 'high'),
('https://dailywire.example.org/article-23', NULL, 'dailywire.example.org', '2025-11-16', '2025-02-25', NULL, 'Other', 'debt_bondage', 126, 'Nepali', 'Chinese', 'Reported incident of debt bondage in an unspecified location.', 'medium'),
('https://dailywire.example.org/article-24', 'Labour abuse allegations surface', 'dailywire.example.org', '2024-10-12', '2024-03-12', 'Nepal', 'South Asia', 'debt_bondage', 259, 'Brazilian', 'Nepali', 'Reported incident of debt bondage in Nepal.', 'medium'),
('https://africareport.example.com/article-25', 'Forced labour case uncovered', 'africareport.example.com', '2025-08-13', NULL, 'South Korea', 'East Asia', 'scam_compound', 21, 'Thai', 'Romanian', 'Reported incident of scam compound in South Korea.', 'medium'),
('https://dailywire.example.org/article-26', 'Investment scam ring dismantled', 'dailywire.example.org', '2025-02-22', '2025-11-13', 'Senegal', 'West Africa', 'sex_trafficking', 355, 'Filipino', NULL, 'Reported incident of sex trafficking in Senegal.', 'low'),
('https://dailywire.example.org/article-27', 'Cross-border ring disrupted', 'dailywire.example.org', '2025-08-16', '2025-03-16', 'Fiji', 'Pacific', 'sex_trafficking', 163, 'Bangladeshi', 'Sudanese', 'Reported incident of sex trafficking in Fiji.', 'medium'),
('https://eastafricawire.example.net/article-28', NULL, 'eastafricawire.example.net', '2024-08-28', '2024-04-05', 'Honduras', 'Central America', 'scam_compound', 114, 'Filipino', NULL, 'Reported incident of scam compound in Honduras.', 'high'),
('https://eastafricawire.example.net/article-29', 'Online scam operation found', 'eastafricawire.example.net', '2024-09-06', '2025-02-13', NULL, 'Other', 'forced_labour', 351, NULL, 'Nepali', 'Reported incident of forced labour in an unspecified location.', 'medium'),
('https://chronicle.example.org/article-30', 'Investment scam ring dismantled', 'chronicle.example.org', '2025-09-01', '2025-07-26', 'Taiwan', 'East Asia', 'pig_butchering', 385, 'Sudanese', 'Bangladeshi', 'Reported incident of pig butchering in Taiwan.', 'high'),
('https://africareport.example.com/article-31', 'Labour abuse allegations surface', 'africareport.example.com', '2024-10-08', '2024-09-01', 'Guatemala', 'Central America', 'forced_labour', 364, 'Kenyan', 'Indian', 'Reported incident of forced labour in Guatemala.', 'high'),
('https://africareport.example.com/article-32', NULL, 'africareport.example.com', '2024-07-30', '2024-03-04', 'Taiwan', 'East Asia', 'pig_butchering', 198, 'Thai', 'American', 'Reported incident of pig butchering in Taiwan.', 'medium'),
('https://eastafricawire.example.net/article-33', 'Arrests in exploitation probe', 'eastafricawire.example.net', '2024-08-13', '2025-09-09', 'Thailand', 'Southeast Asia', 'forced_labour', 138, 'Thai', 'American', 'Reported incident of forced labour in Thailand.', 'low'),
('https://eastafricawire.example.net/article-34', 'Arrests in exploitation probe', 'eastafricawire.example.net', '2025-10-20', NULL, 'Taiwan', 'East Asia', 'other', 235, 'Kenyan', 'Romanian', 'Reported incident of other in Taiwan.', 'medium'),
('https://eastafricawire.example.net/article-35', 'Investment scam ring dismantled', 'eastafricawire.example.net', '2024-08-17', '2024-12-24', 'Nepal', 'South Asia', 'forced_labour', 398, 'Chinese', 'Nigerian', 'Reported incident of forced labour in Nepal.', 'high'),
('https://globalpost.example.net/article-36', 'Labour abuse allegations surface', 'globalpost.example.net', '2025-01-12', '2024-09-19', 'Peru', 'South America', 'scam_compound', 309, 'Nepali', 'Vietnamese', 'Reported incident of scam compound in Peru.', 'medium'),
('https://eastafricawire.example.net/article-37', 'Arrests in exploitation probe', 'eastafricawire.example.net', '2025-12-08', '2025-08-29', 'Cambodia', 'Southeast Asia', 'forced_labour', 123, NULL, 'Nepali', 'Reported incident of forced labour in Cambodia.', 'medium'),
('https://dailywire.example.org/article-38', 'Investment scam ring dismantled', 'dailywire.example.org', '2025-03-06', NULL, 'Guatemala', 'Central America', 'forced_labour', 53, 'Mixed', 'Bangladeshi', 'Reported incident of forced labour in Guatemala.', 'low'),
('https://chronicle.example.org/article-39', 'Cross-border ring disrupted', 'chronicle.example.org', '2024-10-01', '2025-08-29', 'Japan', 'East Asia', 'organ_trafficking', 124, 'Indian', 'Bangladeshi', 'Reported incident of organ trafficking in Japan.', 'high'),
('https://dailywire.example.org/article-40', 'Compound raid frees workers', 'dailywire.example.org', '2024-12-29', '2024-08-05', 'Honduras', 'Central America', 'sex_trafficking', 173, 'Kenyan', 'Sudanese', 'Reported incident of sex trafficking in Honduras.', 'high'),
('https://chronicle.example.org/article-41', 'Labour abuse allegations surface', 'chronicle.example.org', '2024-10-28', '2024-04-05', 'Philippines', 'Southeast Asia', 'pig_butchering', 353, 'Mixed', 'Sudanese', 'Reported incident of pig butchering in Philippines.', 'medium'),
('https://news.example.com/article-42', 'Smuggling route exposed', 'news.example.com', '2024-05-02', '2024-11-19', 'Senegal', 'West Africa', 'pig_butchering', 389, 'Romanian', NULL, 'Reported incident of pig butchering in Senegal.', 'medium'),
('https://dailywire.example.org/article-43', 'Investment scam ring dismantled', 'dailywire.example.org', '2024-11-05', '2024-07-02', 'Sri Lanka', 'South Asia', 'forced_labour', NULL, 'Kenyan', NULL, 'Reported incident of forced labour in Sri Lanka.', 'high'),
('https://africareport.example.com/article-44', 'Investment scam ring dismantled', 'africareport.example.com', '2025-03-27', '2025-05-05', 'Zimbabwe', 'Southern Africa', 'sex_trafficking', 25, 'Egyptian', NULL, 'Reported incident of sex trafficking in Zimbabwe.', 'high'),
('https://africareport.example.com/article-45', 'Migrant workers report abuse', 'africareport.example.com', '2024-09-11', '2024-03-28', 'Nigeria', 'West Africa', 'forced_labour', 390, 'Nigerian', 'American', 'Reported incident of forced labour in Nigeria.', 'medium'),
('https://news.example.com/article-46', 'Online scam operation found', NULL, '2024-07-31', '2024-04-11', 'Saudi Arabia', 'Middle East', 'other', 134, 'Vietnamese', NULL, 'Reported incident of other in Saudi Arabia.', 'medium'),
('https://dailywire.example.org/article-47', 'Trafficking network broken up', 'dailywire.example.org', '2024-03-13', '2025-04-09', 'Cambodia', 'Southeast Asia', 'forced_labour', 134, 'Romanian', 'Nigerian', 'Reported incident of forced labour in Cambodia.', 'low'),
('https://africareport.example.com/article-48', 'Smuggling route exposed', 'africareport.example.com', '2024-05-07', '2025-03-25', 'South Korea', 'East Asia', 'scam_compound', 154, 'Kenyan', 'Egyptian', 'Reported incident of scam compound in South Korea.', 'medium'),
('https://eastafricawire.example.net/article-49', 'Compound raid frees workers', 'eastafricawire.example.net', '2025-08-24', '2025-08-12', 'Cambodia', 'Southeast Asia', 'sex_trafficking', 390, 'Kenyan', 'Vietnamese', 'Reported incident of sex trafficking in Cambodia.', 'medium'),
('https://chronicle.example.org/article-50', 'Online scam operation found', 'chronicle.example.org', '2024-12-22', '2025-04-26', 'Mozambique', 'Southern Africa', 'debt_bondage', 163, 'Vietnamese', 'Egyptian', 'Reported incident of debt bondage in Mozambique.', 'medium'),
('https://news.example.com/article-51', 'Forced labour case uncovered', 'news.example.com', '2025-06-10', '2025-02-17', 'Germany', 'Europe', 'forced_labour', NULL, 'Bangladeshi', 'Romanian', 'Reported incident of forced labour in Germany.', 'medium'),
('https://globalpost.example.net/article-52', 'Trafficking network broken up', 'globalpost.example.net', '2025-12-16', '2025-03-24', 'Uganda', 'East Africa', 'sex_trafficking', 13, 'Nigerian', 'Mexican', 'Reported incident of sex trafficking in Uganda.', 'medium'),
('https://globalpost.example.net/article-53', 'Investment scam ring dismantled', 'globalpost.example.net', '2025-06-05', '2024-10-25', 'Vietnam', 'Southeast Asia', 'scam_compound', 211, 'Egyptian', NULL, 'Reported incident of scam compound in Vietnam.', 'medium'),
('https://chronicle.example.org/article-54', 'Investment scam ring dismantled', 'chronicle.example.org', '2024-09-30', '2025-06-03', 'Japan', 'East Asia', 'forced_labour', 143, 'Egyptian', 'Bangladeshi', 'Reported incident of forced labour in Japan.', 'medium'),
('https://globalpost.example.net/article-55', 'Victims freed in operation', 'globalpost.example.net', '2025-08-08', '2024-09-01', 'Cameroon', 'Central Africa', 'forced_labour', 396, 'Brazilian', 'American', 'Reported incident of forced labour in Cameroon.', 'medium'),
('https://africareport.example.com/article-56', NULL, 'africareport.example.com', '2025-03-26', '2024-04-12', NULL, 'Other', 'forced_labour', NULL, 'Thai', 'British', 'Reported incident of forced labour in an unspecified location.', 'low'),
('https://chronicle.example.org/article-57', 'Forced labour case uncovered', 'chronicle.example.org', '2025-11-21', '2024-12-02', NULL, 'Other', 'forced_labour', 193, 'Egyptian', 'Chinese', 'Reported incident of forced labour in an unspecified location.', 'medium'),
('https://news.example.com/article-58', 'Trafficking suspects detained', 'news.example.com', '2024-04-12', '2025-12-21', 'Philippines', 'Southeast Asia', 'pig_butchering', 354, 'Thai', NULL, 'Reported incident of pig butchering in Philippines.', 'high'),
('https://globalpost.example.net/article-59', 'Online scam operation found', 'globalpost.example.net', '2025-09-16', '2024-03-21', 'Bangladesh', 'South Asia', 'debt_bondage', 316, 'Egyptian', 'Filipino', 'Reported incident of debt bondage in Bangladesh.', 'high'),
('https://eastafricawire.example.net/article-60', 'Victims freed in operation', 'eastafricawire.example.net', '2025-03-28', '2024-03-16', 'Senegal', 'West Africa', 'forced_labour', 299, 'British', 'Bangladeshi', 'Reported incident of forced labour in Senegal.', 'medium'),
('https://eastafricawire.example.net/article-61', 'Forced labour case uncovered', 'eastafricawire.example.net', '2025-02-09', '2025-11-05', 'Taiwan', 'East Asia', 'scam_compound', 288, 'Chinese', 'Egyptian', 'Reported incident of scam compound in Taiwan.', 'medium'),
('https://dailywire.example.org/article-62', 'Labour abuse allegations surface', 'dailywire.example.org', '2025-11-28', '2025-11-06', 'Mexico', 'Central America', 'sex_trafficking', 320, NULL, 'Chinese', 'Reported incident of sex trafficking in Mexico.', 'medium'),
('https://dailywire.example.org/article-63', 'Investment scam ring dismantled', 'dailywire.example.org', '2024-07-24', '2024-06-28', 'Mexico', 'Central America', 'forced_labour', 275, 'Mixed', 'Kenyan', 'Reported incident of forced labour in Mexico.', 'high'),
('https://news.example.com/article-64', 'Investment scam ring dismantled', 'news.example.com', '2024-08-19', NULL, 'Nepal', 'South Asia', 'pig_butchering', 369, 'American', 'Mixed', 'Reported incident of pig butchering in Nepal.', 'high'),
('https://eastafricawire.example.net/article-65', 'Forced labour case uncovered', 'eastafricawire.example.net', '2025-10-15', '2025-01-25', 'Mexico', 'Central America', 'pig_butchering', 54, 'Egyptian', NULL, 'Reported incident of pig butchering in Mexico.', 'medium'),
('https://dailywire.example.org/article-66', 'Victims freed in operation', 'dailywire.example.org', '2024-05-23', '2024-04-29', 'Sri Lanka', 'South Asia', 'debt_bondage', NULL, NULL, 'Nepali', 'Reported incident of debt bondage in Sri Lanka.', 'high'),
('https://africareport.example.com/article-67', 'Trafficking suspects detained', 'africareport.example.com', '2025-02-28', '2024-06-07', 'Sri Lanka', 'South Asia', 'forced_labour', 249, 'Kenyan', NULL, 'Reported incident of forced labour in Sri Lanka.', 'medium'),
('https://africareport.example.com/article-68', NULL, 'africareport.example.com', '2025-01-02', '2025-10-22', 'Taiwan', 'East Asia', 'smuggling', NULL, 'Nepali', 'Bangladeshi', 'Reported incident of smuggling in Taiwan.', 'high'),
('https://globalpost.example.net/article-69', NULL, 'globalpost.example.net', '2024-03-11', '2024-07-29', 'Poland', 'Europe', 'sex_trafficking', 282, 'Romanian', 'Nigerian', 'Reported incident of sex trafficking in Poland.', 'medium'),
('https://africareport.example.com/article-70', 'Migrant workers report abuse', 'africareport.example.com', '2024-04-22', '2024-06-27', 'Honduras', 'Central America', 'scam_compound', 12, NULL, 'Nigerian', 'Reported incident of scam compound in Honduras.', 'medium'),
('https://news.example.com/article-71', 'Cross-border ring disrupted', 'news.example.com', '2025-06-09', '2025-01-05', 'Pakistan', 'South Asia', 'debt_bondage', 230, 'Chinese', 'Sudanese', 'Reported incident of debt bondage in Pakistan.', 'medium'),
('https://news.example.com/article-72', 'Arrests in exploitation probe', 'news.example.com', '2024-03-16', '2025-03-30', 'Nigeria', 'West Africa', 'scam_compound', 163, 'Indian', NULL, 'Reported incident of scam compound in Nigeria.', 'medium'),
('https://africareport.example.com/article-73', 'Smuggling route exposed', 'africareport.example.com', '2024-04-27', '2025-12-19', 'Italy', 'Europe', 'pig_butchering', 332, 'Romanian', 'Nigerian', 'Reported incident of pig butchering in Italy.', 'medium'),
('https://eastafricawire.example.net/article-74', 'Forced labour case uncovered', 'eastafricawire.example.net', '2025-12-04', '2024-06-05', 'Uganda', 'East Africa', 'pig_butchering', 33, NULL, NULL, 'Reported incident of pig butchering in Uganda.', 'medium'),
('https://africareport.example.com/article-75', 'Online scam operation found', 'africareport.example.com', '2025-02-24', '2024-05-05', 'Philippines', 'Southeast Asia', 'pig_butchering', 339, 'British', 'Chinese', 'Reported incident of pig butchering in Philippines.', 'medium'),
('https://news.example.com/article-76', 'Labour abuse allegations surface', 'news.example.com', '2025-01-11', '2025-07-23', 'UK', 'Europe', 'smuggling', 141, 'British', 'Thai', 'Reported incident of smuggling in UK.', 'medium'),
('https://dailywire.example.org/article-77', 'Smuggling route exposed', 'dailywire.example.org', '2024-05-26', NULL, 'Saudi Arabia', 'Middle East', 'forced_labour', 204, NULL, 'Thai', 'Reported incident of forced labour in Saudi Arabia.', 'high'),
('https://eastafricawire.example.net/article-78', 'Migrant workers report abuse', 'eastafricawire.example.net', '2025-09-02', '2025-08-04', 'Mexico', 'Central America', 'pig_butchering', NULL, NULL, NULL, 'Reported incident of pig butchering in Mexico.', 'medium'),
('https://globalpost.example.net/article-79', 'Victims freed in operation', 'globalpost.example.net', '2024-12-19', '2024-04-26', 'Cambodia', 'Southeast Asia', 'forced_labour', 144, 'Egyptian', 'Mexican', 'Reported incident of forced labour in Cambodia.', 'high'),
('https://dailywire.example.org/article-80', 'Migrant workers report abuse', 'dailywire.example.org', '2025-05-24', '2024-01-08', 'China', 'East Asia', 'scam_compound', 88, NULL, 'Nigerian', 'Reported incident of scam compound in China.', 'medium'),
('https://chronicle.example.org/article-81', 'Compound raid frees workers', 'chronicle.example.org', '2025-08-12', '2024-11-16', 'Zambia', 'Southern Africa', 'scam_compound', 206, 'British', 'American', 'Reported incident of scam compound in Zambia.', 'high'),
('https://news.example.com/article-82', 'Trafficking suspects detained', 'news.example.com', '2024-09-06', '2024-04-18', NULL, 'Other', 'smuggling', 204, 'American', 'Brazilian', 'Reported incident of smuggling in an unspecified location.', 'high'),
('https://dailywire.example.org/article-83', 'Cross-border ring disrupted', 'dailywire.example.org', '2024-05-31', '2025-10-22', 'Pakistan', 'South Asia', 'sex_trafficking', 73, 'Vietnamese', 'Indian', 'Reported incident of sex trafficking in Pakistan.', 'high'),
('https://africareport.example.com/article-84', 'Online scam operation found', 'africareport.example.com', '2024-11-26', '2025-10-01', 'Papua New Guinea', 'Pacific', 'forced_labour', 320, 'Bangladeshi', NULL, 'Reported incident of forced labour in Papua New Guinea.', 'medium'),
('https://news.example.com/article-85', 'Smuggling route exposed', 'news.example.com', '2024-10-20', NULL, 'UK', 'Europe', 'sex_trafficking', NULL, 'Indian', 'Sudanese', 'Reported incident of sex trafficking in UK.', 'medium'),
('https://africareport.example.com/article-86', 'Labour abuse allegations surface', 'africareport.example.com', '2024-03-04', '2024-06-03', 'Nigeria', 'West Africa', 'forced_labour', 174, 'Indian', 'Vietnamese', 'Reported incident of forced labour in Nigeria.', 'high'),
('https://dailywire.example.org/article-87', 'Forced labour case uncovered', 'dailywire.example.org', '2025-11-26', '2024-12-12', 'Nepal', 'South Asia', 'forced_labour', 322, 'Indian', 'American', 'Reported incident of forced labour in Nepal.', 'medium'),
('https://dailywire.example.org/article-88', 'Migrant workers report abuse', 'dailywire.example.org', '2025-11-09', '2025-12-16', 'Sri Lanka', 'South Asia', 'pig_butchering', 303, 'Indian', 'American', 'Reported incident of pig butchering in Sri Lanka.', 'low'),
('https://africareport.example.com/article-89', 'Trafficking suspects detained', 'africareport.example.com', '2025-11-17', NULL, 'Mexico', 'Central America', 'sex_trafficking', 184, NULL, 'Romanian', 'Reported incident of sex trafficking in Mexico.', 'medium'),
('https://news.example.com/article-90', 'Migrant workers report abuse', NULL, '2025-06-03', '2024-04-13', 'Papua New Guinea', 'Pacific', 'scam_compound', 377, 'Chinese', 'Filipino', 'Reported incident of scam compound in Papua New Guinea.', 'medium'),
('https://globalpost.example.net/article-91', 'Online scam operation found', 'globalpost.example.net', '2025-02-24', '2024-02-14', 'Ethiopia', 'East Africa', 'scam_compound', 367, 'Bangladeshi', 'Bangladeshi', 'Reported incident of scam compound in Ethiopia.', 'high'),
('https://africareport.example.com/article-92', 'Trafficking network broken up', 'africareport.example.com', '2024-10-15', '2025-04-17', 'Zambia', 'Southern Africa', 'organ_trafficking', 256, 'Vietnamese', 'Filipino', 'Reported incident of organ trafficking in Zambia.', 'medium'),
('https://dailywire.example.org/article-93', 'Cross-border ring disrupted', 'dailywire.example.org', '2024-06-13', NULL, 'Vietnam', 'Southeast Asia', 'forced_labour', 261, NULL, 'Nigerian', 'Reported incident of forced labour in Vietnam.', 'medium'),
('https://news.example.com/article-94', 'Trafficking network broken up', 'news.example.com', '2024-11-22', '2024-01-29', 'Qatar', 'Middle East', 'forced_labour', 364, 'Filipino', NULL, 'Reported incident of forced labour in Qatar.', 'medium'),
('https://news.example.com/article-95', 'Victims freed in operation', 'news.example.com', '2024-09-19', '2024-01-20', 'Egypt', 'Middle East', 'forced_labour', 75, 'Sudanese', 'Mexican', 'Reported incident of forced labour in Egypt.', 'high'),
('https://news.example.com/article-96', 'Victims freed in operation', NULL, '2025-09-03', '2025-05-26', 'India', 'South Asia', 'sex_trafficking', 322, 'Nigerian', 'Mexican', 'Reported incident of sex trafficking in India.', 'medium'),
('https://dailywire.example.org/article-97', 'Labour abuse allegations surface', 'dailywire.example.org', '2025-06-22', NULL, 'Thailand', 'Southeast Asia', 'forced_labour', 258, 'American', 'Chinese', 'Reported incident of forced labour in Thailand.', 'low'),
('https://dailywire.example.org/article-98', NULL, 'dailywire.example.org', '2025-10-05', '2025-11-03', 'Tanzania', 'East Africa', 'pig_butchering', 296, 'Brazilian', NULL, 'Reported incident of pig butchering in Tanzania.', 'medium'),
('https://globalpost.example.net/article-99', 'Trafficking suspects detained', 'globalpost.example.net', '2025-04-13', '2024-03-05', 'Zimbabwe', 'Southern Africa', 'smuggling', NULL, 'Romanian', 'Brazilian', 'Reported incident of smuggling in Zimbabwe.', 'medium'),
('https://news.example.com/article-100', 'Trafficking network broken up', 'news.example.com', '2024-10-06', '2024-12-05', 'Mozambique', 'Southern Africa', 'pig_butchering', 187, 'American', 'American', 'Reported incident of pig butchering in Mozambique.', 'medium');